### ISSUE TITLE
/component/Header

### ISSUE THREAD

**Issue by saliejung** [weianofsteel/saliejung#2]
1. Text (work, about...) on the header should be all caps.
2. **When hovering**, remove the underlined, make the gray text change to black text.
3. Letter-spacing: 2%

*impact across the site

**Comment by weianofsteel** [comment]
Letter-spacing: 2% 是menu的字與字之間嗎，有包括大標題嗎，還是按鈕與按鈕之間？

**Comment by saliejung** [comment]
按鈕本身的字（e.g. WORK, W 和 O 之間的距離是 letter-spacing），不是按鈕之間

**Comment by saliejung** [comment]
- [ ] text style please change to the following

```
    font-size: 18px;
    letter-spacing: 1px;
```

- [ ] please make sure the spacing between each menu button is 32px approximately
