### ISSUE TITLE
Work/Teamson: 修改 caption 文字

### ISSUE THREAD

**Issue by saliejung** [weianofsteel/saliejung#75]
這四張圖片的 caption 還是沒改到！！！

![image](https://user-images.githubusercontent.com/30551196/107226925-5241c480-6a4d-11eb-8bb2-4cbf2236e62b.png)

**Comment by weianofsteel** [comment]
![截圖 2021-02-09 上午9 28 33](https://user-images.githubusercontent.com/52395751/107302994-2fe59080-6ab9-11eb-8670-5fe1ebbe9a0f.png)

**Comment by weianofsteel** [comment]
這個數字不對嗎

**Comment by saliejung** [comment]
我說文字內容 = =
